services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./db:/var/lib/mysql
    command: "--default-authentication-plugin=mysql_native_password"
    healthcheck:
      test: "mysql -uroot -p$MYSQL_ROOT_PASSWORD -e 'select 1'"
      interval: 1s
      retries: 120
    networks:
      - wplocal-network

  wordpress:
    depends_on:
      - db
    build:
      args:
        user: mandlenkosi
        uid: 1000
      context: ./
      dockerfile: wordpress.dockerfile
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./app:/var/www/html
    networks:
      - wplocal-network

  webserver:
    depends_on:
      - wordpress
      - db
    build:
      args:
        user: mandlenkosi
        uid: 1000
      context: ./
      dockerfile: nginx.dockerfile
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8089:80"
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./app:/var/www/html
    networks:
      - wplocal-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    env_file: .env
    ports:
      - 8180:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
      - wplocal-network

  wp:
    container_name: wpcli
    working_dir: /var/www/html
    image: wordpress:cli
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_USER=$MYSQL_USER
    depends_on:
      db:
        condition: service_healthy
    user: 1000:1000
    entrypoint: ["wp"]
    volumes:
      - ./app:/var/www/html
      - ./db:/var/lib/mysql
    networks:
      - wplocal-network

networks:
  wplocal-network:
    driver: bridge
